name: build sandbox

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        tags: ghcr.io/vives-projectwerk-2021/pulu-sandbox:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max